name: Publish npm Package

on:
  workflow_dispatch: # This allows the workflow to be triggered manually

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Specify the Node.js version 20

      - name: Install dependencies
        run: npm install

      - name: Build the package
        run: npm run build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Use NPM_TOKEN secret for authentication
        run: npm publish --access public
